apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejsapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: sanjeevkt720/prometheus-demo
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    job: node-api
    app: nodejsapp
spec:
  selector:
    app: nodejsapp
  ports:
    - name: web 
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: severice-nodejs-service
  labels:
    release: promeheus
    app: promeheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s 
      port: web
      path: /swagger-stats/metrics
  selector:
    matchLabels:
      app: nodejsapp
---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: severice-nodejs-service
  labels:
    release: promeheus
spec:
  groups:
    - name: api
      rules:
        - alert: down
          expr: up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Prometheus target missing {{ $labels.instance }}